[providers.python]
version = "3.11"

[phases.setup]
nixPkgs = ["postgresql"]

[phases.install]
cmds = [
  "cd backend && python -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd backend && python manage.py collectstatic --no-input",
  "cd backend && python manage.py migrate --no-input"
]

[start]
cmd = "cd backend && gunicorn tanorin_backend.wsgi:application"
