[phases.build]
cmds = [
  "...",
  "cd backend && python manage.py collectstatic --no-input",
  "cd backend && python manage.py migrate --no-input"
]

[start]
cmd = "cd backend && python -m gunicorn tanorin_backend.wsgi:application"
