[phases.build]
cmds = [
  "cd backend && python3 manage.py collectstatic --no-input",
  "cd backend && python3 manage.py migrate --no-input"
]

[start]
cmd = "cd backend && python3 -m gunicorn tanorin_backend.wsgi:application"
