providers = ["python"]

[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "python3 -m venv venv",
  "./venv/bin/pip install --upgrade pip",
  "./venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd backend && /app/venv/bin/python manage.py collectstatic --no-input",
  "cd backend && /app/venv/bin/python manage.py migrate --no-input"
]

[start]
cmd = "cd backend && /app/venv/bin/python manage.py loaddata db_dump.json && /app/venv/bin/python create_admin.py && /app/venv/bin/gunicorn tanorin_backend.wsgi:application"
