services:
  - type: web
    name: tanorin-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn tanorin_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2

  - type: web
    name: tanorin-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: tanorin-backend
          property: url
